### ISSUE TITLE
Support minimum php 5.3 version as Give does.

### ISSUE THREAD

**Issue by ravinderk** [tw2113/QueryMonitor-GiveWP#4]
@tw2113 Give support minimum PHP 5.3  and it will be good if this addon does same. I was planning to use this but can not use this with PHP version limitation.

For ref: https://github.com/tw2113/QueryMonitor-GiveWP/blob/master/query-monitor-givewp.php#L40

**Comment by tw2113** [comment]
While I was looking forward to short array syntax, I understand the idea here for compatible minimum versions, and have pushed up changes to make it PHP5.3 ready. thanks @ravinderk
